### PR TITLE
 New Ground Radar Map - Bay Numbers (reopened, closed by mistake)

### PR DESCRIPTION
**Pull request by pheonixtaylor**
Included all parking positions w/coordinates available for controlled positions. Alphabetical order from DAP, charts separated by one line break, airports by three line breaks & a five line break is between DAP & MIL TERMA Plates.
Minor Conflicts/Overlaps with ASMGCS_TAXI_ALL| -- Fixed with change to "Maps/ASMGCS_TAXI_ALL.xml" | Adjusted positions of overlapping parking positions. Wasn't able to nudge the coordinates so I've had to use a different format for coordinates.

Other Comments:
YPTN'S Coords aren't precise.
YMES's Coords also not precise however parking positions would overlap each other, decided not to include.
YAMB,YNSW&YSRI Coords are maybe 75% as accurate as ones found in the DAP.

-- New pull request as I had closed the previous PR by mistake whilst trying to make another PR for a YPDN_RTCC.

### CODE REVIEW

**Comment by vatpacais** [comment]
Thanks Pheonx, great concept. Before I seek agreement to add this map, I need the process for maintaining it as bay numbers change over time and if we publish the map, we have to keep it up to date from publicly available sources  without too much overhead.
I'd appreciate your thoughts on how we can easily check for updates to this data, going through all the DAP parking pages looking for amendments would be a major overhead for us, apart from the format not being easily read when converted to text.

**Comment by pheonixtaylor** [comment]
I think the easiest way to keep the map updated would be keeping an eye on the AIP SUP & AICs and before a major airac revision check on the Pending Charts to see if any Apron Charts have been updated/added. In the latest commit I've added Airport and Apron Chart names above the individual parking positions, this should allow someone easier access to the correct part of the file to edit. This is someone I'll be monitoring and will make changes as required.

**Comment by vatpacais** [comment]
> YPTN'S Coords aren't precise.
> YMES's Coords also not precise however parking positions would overlap each other, decided not to include.
> YAMB,YNSW&YSRI Coords are maybe 75% as accurate as ones found in the DAP.

Does this mean that you haven't used the DAP coordinates for these airports?

**Comment by pheonixtaylor** [comment]
YPTN coordinates are from the DAP, they are just not very precise when compared to others found in the DAP. This is likely because it's a joint base but doesn't see much traffic. They were included as they didn't overlap and Tindal doesn't see much traffic anyway. (I don't believe TN_GND or TN_DEL even have AFV positions). 

The coordinates below were found in the (Mil AIP) TERMA.
YMES has coordinates on an Aerodrome Chart many of which have the exact same coordinates eg: 8. S38 05.9 E147 07.9 & 9. S38 05.9 E147 07.9. I thought that there was no point including these as they would overlap and make the inclusion of them wouldn't be of any value.
I simply observed that YAMB, YNSW & YSRI's coordinates found on Apron Charts were not as accurate as the majority of positions found in the DAP.

**Comment by vatpacais** [comment]
OK, From what you have said, all coordinates are from the DAP.
I assume you didn't manually enter all these, are you willing to share the application which extracted the data from the DAP charts?

I'll need more time to review the Map and our existing aerodrome charts. At first glance, the YMML aerodrome map will need updating as Taxi S will be broken by an extended apron for parking positions F21 to F25A, there may be more. This map won't make AIRAC2207. Keep this request open, I can easily redirect it to a future AIRAC branch.

**Comment by vatpacais** [comment]
> Let me know what's needed from me, if needed I can go in and manually adjust the major issues if that isn't going to break anything else.

Thanks, it's easier for us to update our master airport .klm files to produce the ground layout updates for vatsys and Euroscope.
I'll seek agreement on whether we incorporate this map in our dataset

**Comment by vatpacais** [comment]
Thanks Pheonix

**Pull request merged**
